spring:
  profiles:
    active: local

---
spring:
  profiles: local
  kafka:
    producer:
      bootstrap-servers: 172.17.162.180:9092
      buffer-memory: 40960
      batch-size: 4096
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 172.17.162.180:9092
      enable-auto-commit: false
      group-id: dc_consumer_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging:
  path: ./
  file: test
temp:
  path: /developer/test_env/tmpfile/test
server:
  port: 8989
res:
  path: C:\developer\test_env\config.properties


---
spring:
  profiles: prod
logging:
  path: /mnt/data/logback/test
  file: test
temp:
  path: /mnt/var/www/website/test
server:
  port: 8989